### ISSUE TITLE
Engineer - Swerve

### ISSUE THREAD

**Issue by Fairo20** [TAMU-Robomasters/aimbots-dev#18]

**Comment by jpostelnik** [comment]
31 days till this has to be done... as i promised nathaniel

**Comment by jpostelnik** [comment]
So the basic swerve code is done. All of the yaw motors need to be tuned so they are at 0 is the same spot. 

Testing is on hold due to smelling magic smoke and breaking engineer. 

Current engineer movement:
https://user-images.githubusercontent.com/57419716/196745407-d43d6c06-5ac7-45e9-aa5c-fbb687009345.mov
