### ISSUE TITLE
Robot States

### ISSUE THREAD

**Issue by Fairo20** [TAMU-Robomasters/aimbots-dev#44]
Define the robot object (including self), instantiation, and storage.

**Comment by jpostelnik** [comment]
What is needed for the robot state? This is what I currently have.

`robotType type;
   int number;
   int x,y,z;

   int health;`

**Comment by jpostelnik** [comment]
Now that `feature/ref-protocal` has been merged in its time to start working on making actual messages!

**Comment by jpostelnik** [comment]
Add methods to update an array of 115 length that can be requested by the output message subsystem. It breaks down all of the values into those of uint8_t from uint16_t through bit shifting. I am unsure that if the bit shift is 100% correct in the code. It is math wise though. Still need to have it so that it hooks into the actual subsystem of the communication response handler. Might also be smart to either write one for each message type or just rename `communication_response` so that it is more understandable.

**Comment by jpostelnik** [comment]
TODOS:

- [ ] Finish the methods for receiving all of the data and storing it appropriately
- [ ] Make methods in `communication_response_handler` for the message that was received
- [ ] Hook the message creator with `comuincation_response_subsystem` 
- [ ] add localization code and hook it in with the rest of the `RobotStates` subsystems
- [ ] Fix the spelling and the naming convention of all of it because right now it looks like a mess and is very clogged

**Comment by jpostelnik** [comment]
merged to main
